local c = require("theme").colors
local color = require("color")

-- Editor.
vim.api.nvim_set_hl(0, "CurSearch", { bg = c.orange, fg = c.black })
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = c.red })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = c.yellow })
vim.api.nvim_set_hl(0, "Directory", { fg = c.blue })
vim.api.nvim_set_hl(0, "EndOfBuffer", { fg = c.bg })
vim.api.nvim_set_hl(0, "Error", { fg = c.red })
vim.api.nvim_set_hl(0, "ErrorMsg", { fg = c.red })
vim.api.nvim_set_hl(0, "FloatBorder", { fg = color.darken(c.turquoise, 0.2) })
vim.api.nvim_set_hl(0, "FloatTitle", { fg = color.darken(c.turquoise, 0.2), bold = true })
vim.api.nvim_set_hl(0, "Folded", { bg = "none" })
vim.api.nvim_set_hl(0, "LineNr", { fg = color.darken(c.comment, 0.5) })
vim.api.nvim_set_hl(0, "MatchParen", { fg = c.orange, bold = true })
vim.api.nvim_set_hl(0, "Normal", { fg = c.fg, bg = "none" })
vim.api.nvim_set_hl(0, "NormalFloat", { link = "Normal" })
vim.api.nvim_set_hl(0, "Question", { fg = c.blue })
vim.api.nvim_set_hl(0, "QuickFixLine", { link = "Visual" })
vim.api.nvim_set_hl(0, "Search", { bg = c.blue, fg = c.black })
vim.api.nvim_set_hl(0, "StatusLine", { bg = c.bar.bg_dark })
vim.api.nvim_set_hl(0, "TabLine", { bg = c.bar.bg_light, fg = c.bar.fg })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = c.bar.bg_dark })
vim.api.nvim_set_hl(0, "TabLineSel", { fg = c.bar.bg_light, bg = c.accent })
vim.api.nvim_set_hl(0, "Title", { fg = c.blue, bold = true })
vim.api.nvim_set_hl(0, "Visual", { bg = color.darken(c.comment, 0.8) })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = c.black })

-- Syntax.
vim.api.nvim_set_hl(0, "Character", { fg = c.green })
vim.api.nvim_set_hl(0, "Comment", { fg = c.comment })
vim.api.nvim_set_hl(0, "Constant", { fg = c.orange })
vim.api.nvim_set_hl(0, "Delimiter", { fg = c.turquoise })
vim.api.nvim_set_hl(0, "Function", { fg = c.blue })
vim.api.nvim_set_hl(0, "Identifier", { fg = c.turquoise })
vim.api.nvim_set_hl(0, "Operator", { fg = c.cyan })
vim.api.nvim_set_hl(0, "PreProc", { fg = c.cyan })
vim.api.nvim_set_hl(0, "Special", { fg = c.turquoise })
vim.api.nvim_set_hl(0, "Statement", { fg = c.magenta })
vim.api.nvim_set_hl(0, "String", { fg = c.green })
vim.api.nvim_set_hl(0, "Type", { fg = c.turquoise })
vim.api.nvim_set_hl(0, "Todo", { fg = c.blue, bold = true })

-- Diff.
vim.api.nvim_set_hl(0, "Added", { fg = c.git.add })
vim.api.nvim_set_hl(0, "Changed", { fg = c.git.change })
vim.api.nvim_set_hl(0, "DiffAdd", { bg = color.darken(c.git.add, 0.8) })
vim.api.nvim_set_hl(0, "DiffChange", { bg = color.darken(c.git.change, 0.8) })
vim.api.nvim_set_hl(0, "DiffDelete", { bg = color.darken(c.git.delete, 0.8) })
vim.api.nvim_set_hl(0, "DiffText", { bg = color.darken(c.git.change, 0.6) })
vim.api.nvim_set_hl(0, "Removed", { fg = c.git.delete })
vim.api.nvim_set_hl(0, "diffAdded", { fg = c.git.add })
vim.api.nvim_set_hl(0, "diffChanged", { fg = c.git.change })
vim.api.nvim_set_hl(0, "diffNewFile", { fg = c.orange })
vim.api.nvim_set_hl(0, "diffOldFile", { fg = c.yellow })
vim.api.nvim_set_hl(0, "diffRemoved", { fg = c.git.delete })
