local color = require("color")
local c = require("theme").colors

-- Main.
vim.api.nvim_set_hl(0, "Normal", { fg = c.fg, bg = "none" })
vim.api.nvim_set_hl(0, "NormalFloat", { link = "Normal" })

-- Editor.
vim.api.nvim_set_hl(0, "CurSearch", { bg = c.orange, fg = c.black })
vim.api.nvim_set_hl(0, "DiffAdd", { bg = color.darken(c.git.add, 0.8) })
vim.api.nvim_set_hl(0, "DiffChange", { bg = color.darken(c.git.change, 0.8) })
vim.api.nvim_set_hl(0, "DiffDelete", { bg = color.darken(c.git.delete, 0.8) })
vim.api.nvim_set_hl(0, "DiffText", { bg = color.darken(c.git.change, 0.6) })
vim.api.nvim_set_hl(0, "Directory", { fg = c.blue })
vim.api.nvim_set_hl(0, "EndOfBuffer", { fg = c.bg })
vim.api.nvim_set_hl(0, "ErrorMsg", { fg = c.red })
vim.api.nvim_set_hl(0, "FloatBorder", { fg = color.darken(c.turquoise, 0.2) })
vim.api.nvim_set_hl(0, "FloatTitle", { fg = color.darken(c.turquoise, 0.2), bold = true })
vim.api.nvim_set_hl(0, "Folded", { bg = "none" })
vim.api.nvim_set_hl(0, "LineNr", { fg = color.darken(c.comment, 0.5) })
vim.api.nvim_set_hl(0, "MatchParen", { fg = c.orange, bold = true })
vim.api.nvim_set_hl(0, "Question", { fg = c.blue })
vim.api.nvim_set_hl(0, "QuickFixLine", { link = "Visual" })
vim.api.nvim_set_hl(0, "Search", { bg = c.blue, fg = c.black })
vim.api.nvim_set_hl(0, "TabLine", { bg = c.bar.bg_light, fg = c.bar.fg })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = c.bar.bg_dark })
vim.api.nvim_set_hl(0, "TabLineSel", { fg = c.bar.bg_light, bg = c.accent })
vim.api.nvim_set_hl(0, "Title", { fg = c.blue, bold = true })
vim.api.nvim_set_hl(0, "Visual", { bg = color.darken(c.comment, 0.7) })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = c.black })

vim.api.nvim_set_hl(0, "diffAdded", { fg = c.git.add })
vim.api.nvim_set_hl(0, "diffChanged", { fg = c.git.change })
vim.api.nvim_set_hl(0, "diffNewFile", { fg = c.orange })
vim.api.nvim_set_hl(0, "diffOldFile", { fg = c.yellow })
vim.api.nvim_set_hl(0, "diffRemoved", { fg = c.git.delete })

-------------------------------------------------------------------------------
-- vim.api.nvim_set_hl(0, "Conceal", { fg = c.dark5 })
-- vim.api.nvim_set_hl(0, "FoldColumn", { fg = c.comment })
-- vim.api.nvim_set_hl(0, "ModeMsg", { fg = c.fg_dark, bold = true })
-- vim.api.nvim_set_hl(0, "MoreMsg", { fg = c.blue })
-- vim.api.nvim_set_hl(0, "MsgArea", { fg = c.fg_dark })
-- vim.api.nvim_set_hl(0, "NonText", { fg = c.dark3 })
-- vim.api.nvim_set_hl(0, "NormalNC", { fg = c.fg })
-- vim.api.nvim_set_hl(0, "NormalSB", { fg = c.fg_sidebar, bg = c.bg_sidebar })
-- vim.api.nvim_set_hl(0, "PmenuThumb", { bg = c.fg_gutter })
-- vim.api.nvim_set_hl(0, "SignColumn", { fg = c.red })
-- vim.api.nvim_set_hl(0, "SignColumnSB", { bg = c.bg_sidebar, fg = c.fg_gutter })
-- vim.api.nvim_set_hl(0, "SpecialKey", { fg = c.dark3 })
-- vim.api.nvim_set_hl(0, "SpellBad", { sp = c.error, undercurl = true })
-- vim.api.nvim_set_hl(0, "SpellCap", { sp = c.warning, undercurl = true })
-- vim.api.nvim_set_hl(0, "SpellLocal", { sp = c.info, undercurl = true })
-- vim.api.nvim_set_hl(0, "SpellRare", { sp = c.hint, undercurl = true })
-- vim.api.nvim_set_hl(0, "StatusLine", { fg = c.fg_sidebar, bg = c.bg_statusline })
-- vim.api.nvim_set_hl(0, "StatusLineNC", { fg = c.fg_gutter, bg = c.bg_statusline })
-- vim.api.nvim_set_hl(0, "Substitute", { bg = c.red, fg = c.black })
-- vim.api.nvim_set_hl(0, "VertSplit", { fg = c.border })
-- vim.api.nvim_set_hl(0, "VisualNOS", { bg = c.bg_visual })
-- vim.api.nvim_set_hl(0, "WarningMsg", { fg = c.warning })
-- vim.api.nvim_set_hl(0, "Whitespace", { fg = c.fg_gutter })
-- vim.api.nvim_set_hl(0, "WildMenu", { bg = c.bg_visual })
-- vim.api.nvim_set_hl(0, "WinBar", { link = "StatusLine" })
-- vim.api.nvim_set_hl(0, "WinBarNC", { link = "StatusLineNC" })
-- vim.api.nvim_set_hl(0, "lCursor", { fg = c.bg, bg = c.fg })

-- Syntax.
vim.api.nvim_set_hl(0, "Character", { fg = c.green })
vim.api.nvim_set_hl(0, "Comment", { fg = c.comment })
vim.api.nvim_set_hl(0, "Constant", { fg = c.orange })
vim.api.nvim_set_hl(0, "Delimiter", { fg = c.turquoise })
vim.api.nvim_set_hl(0, "Function", { fg = c.blue })
vim.api.nvim_set_hl(0, "Identifier", { fg = c.turquoise })
vim.api.nvim_set_hl(0, "Operator", { fg = c.cyan })
vim.api.nvim_set_hl(0, "PreProc", { fg = c.cyan })
vim.api.nvim_set_hl(0, "Special", { fg = c.turquoise })
vim.api.nvim_set_hl(0, "Statement", { fg = c.magenta })
vim.api.nvim_set_hl(0, "String", { fg = c.green })
vim.api.nvim_set_hl(0, "Type", { fg = c.turquoise })

vim.api.nvim_set_hl(0, "Error", { fg = c.red })
vim.api.nvim_set_hl(0, "Todo", { fg = c.blue, bold = true })
vim.api.nvim_set_hl(0, "Underlined", { underline = true })

vim.api.nvim_set_hl(0, "DiagnosticError", { fg = c.red })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = c.yellow })
